language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- '4.0'
- '5.0'
- iojs
after_script: npm install codecov.io && cat ./coverage/lcov.info | codecov
sudo: false
deploy:
  provider: releases
  api_key:
    secure: kyGB0YxfKCMEZjl+HtoQtNAURLo7x9x7Def3jklkjBRIpc93BTG8dT2L07YZ8ZZ2OtIFKwhIP5m8K4wWoPOzl80lB4fEyI+AzG112bONYNyuNRUCvFAXVt3tPi3avW+gf0zKVQm7wzkhsdv5dBQ/DcJaxe6ETt9mYc4Pdpc5Qu+g2IZ/XjaM5bp/M9HPds80Mx1D2Grq5SDxZRgoCOOrWAP0NJdHO+CrQhy1hpDz3xtWwijDf3WCcqbs4RzHxZamEoKI6lbB1Qf4vv9JW6MLKGBCTEQmWNAusrVZoTtGuO8K7ku3eHXf339pdecSSKVOAxk8bVoCtkQYWWp8lL6ZPFrXG+RajKVmFcYnRDOpPKooG9jU5lL8L9iUupuf8lZ5lz86u86foYUuKgYifF8ClPGtpBMwRLViZw1bEzyOwmjbvxhBwTQpq2FIYTt8dKrhk3sNjPnJi4wbj7b1zHcuAqmtBGQNY/EeJizL5OhUfrRMBlhaDLsEnVlsdoIlrUayK6jRJV0tVqDa0rSabouh/fjqn2+PQXM2UTshfE9vtFgPNYE3UcX58l6uj1mFKiHKts17f3D/XDTtdn5iQif1FsIjwwj9uBfUl7DlHW5CIJOPbVujzScTSFMng5aS4TdhGIUr61MvbdLdySLraGUnm+k9RA/TZAOApL2ZbglhXh0=
  file:
    - "vfile.js"
    - "vfile.min.js"
  on:
    tags: true
